name: gitleaks

on:
  pull_request:
    branches:
      - main
 
jobs:
  scan:
    name: gitleaks-try-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
          GITLEAKS_CONFIG: ${{ github.workspace }}/.github/gitleaks.toml
          GITLEAKS_EXIT_CODE: 0
