name: Gitleaks Secret Scan

on:
  pull_request:
    branches: [main]

jobs:
  scan:
    name: gitleaks-action-HEAD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        config-path: .github/gitleaks.toml  # Optional: Use your own config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
