name: gitleaks-docker

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Allow commenting on PRs
      issues: write          # For creating/updating comments
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gitleaks-docker
        run: |
          docker pull zricethezav/gitleaks:latest
          docker run -v ${{ github.workspace }}:/repo zricethezav/gitleaks:latest detect --source=/repo --verbose --exit-code=0 -f=json > gitleaks-results.json
          cat gitleaks-results.json
      
      - name: Display Gitleaks JSON Output
        run: |
         echo "Displaying raw Semgrep results..."
         cat gitleaks-results.json
