name: gitleaks-try-1
on:
  pull_request:

jobs:
  scan:
    name: gitleaks-action-HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./ # Runs the action that's in the root directory of the repo checked out above. i.e. This action itself.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
