name: gitleaks-action-HEAD

on:
  pull_request:
    branches:
      - main
      
jobs:
  scan:
    name: gitleaks-action-HEAD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
