name: Gitleaks Secret Scan

on:
  workflow_call:

jobs:
  gitleaks:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important to scan entire git history

    - name: Download required files
      env:
        GH_TOKEN: ${{ github.token }}
      run : |
        content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/.github/gitleaks.toml > gitleaks.toml
        content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/action.yml > action.yml
        content=`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/scriptkidakash81/example/dist/index.js > index.js

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .github/gitleaks.toml  # Optional: Use your own config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
