name: Gitleaks using go install

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install latest Gitleaks
        run: |
          go install github.com/zricethezav/gitleaks@latest
          which gitleaks
          
          # Verify
          /usr/bin/gitleaks version

      - name: Run Gitleaks with custom exit code
        run: |
          /usr/bin/gitleaks detect -v --exit-code=0 -f=json > gitleaks-results.json

      - name: Display Gitleaks JSON Output
        run: |
         echo "Displaying Gitleaks results..."
         cat gitleaks-results.json
